# Generated by Django 2.2.4 on 2022-09-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='book_auth_app.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='decs',
            field=models.TextField(null=True),
        ),
    ]
